version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: usersdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: pass
      DB_NAME: usersdb
    depends_on:
      - db
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
